### ISSUE TITLE
Hervin: Create handlebars views

### ISSUE THREAD

**Issue by rarmatei** [rarmatei/progress-tracker#1]
Create the handlebars directory structure and views for the following pages:

- The "Progress Tracker" header (from the screenshot homepage)
- A homepage (containing the table of views and also the Add and Edit buttons)
- Edit Page
- Add Topic Page
- Form partial

**Comment by rarmatei** [comment]
I left this open as we still need to convert the comments in the views to HTML comments. Hervin, can you please take care of that?

**Comment by cardona6** [comment]
yes, I will do it
