### ISSUE TITLE
Hervin: ensure API endpoints work

### ISSUE THREAD

**Issue by rarmatei** [rarmatei/progress-tracker#22]
Now that we have your Mongoose model in, and Mohammad's API endpoints, we need to test they work correctly. So please try and follow these steps:

Run the server
Submit a Postman request to:
- Add Topic: POST request to `/api/topics`
- Delete Topic: DELETE request to `/api/topics/:id`
- Edit Topic: PUT request to `api/topics/:id`

Have a database running while submitting these requests. 
Confirm that once you submit the Postman request, the database changes accordingly by printing out the collection in your console.
Close this issue once it's working, or submit a PR with the code fixes, if needed.

**Comment by cardona6** [comment]
I can confirm  everything works.
